### ISSUE TITLE
get_environments.rb is empty

### ISSUE THREAD

**Issue by stjeanp** [fog/fog-ecloud#5]
The get_environments.rb file is empty. Looks like something got broken during the mass rename.

**Comment by plribeiro3000** [comment]
[this](https://github.com/fog/fog/blob/19c712a0b0d449c0e0cceaf94e3ee8703814db32/lib/fog/ecloud/requests/compute/get_environments.rb) is from a commit where `ecloud` was still in `fog`.

So this appears to be an old issue, not form the mass rename change.

**Comment by stjeanp** [comment]
I'm closing this. It looks like the get_environments request is never made, so that file's not needed.
